### ISSUE TITLE
Add webpack.config.js

### ISSUE THREAD

**Issue by maksrom** [AndriyNovak/Front-end-Advanced#1]
As a developer I want to build applications.

Here is a webpack.config.js file which I've already tested.
```
var path    = require('path');
module.exports = {
    entry: './main.js',
    output: {
        filename: 'build.js',
        path: path.join(__dirname, '/dist')
    },
};
```

Also, do not forget about npm init to create package.json file with 
```
 "scripts": {
    "start": "webpack"
  },
```
part which helps you to run correct webpack package. `

**Comment by AndriyNovak** [comment]
is done

**Comment by maksrom** [comment]
@AndriyNovak please, close this issue if it's done =)
