### ISSUE TITLE
Remove node_modules folder

### ISSUE THREAD

**Issue by maksrom** [AndriyNovak/Front-end-Advanced#2]
I suggest to make 2 different commits:

1. Remove node_modules
2. Update .gitignore to disable tracking of system files

Here you can find an example of perfect .gitignore file. You can use it if you want =)
https://github.com/github/gitignore/blob/master/Node.gitignore

**Comment by AndriyNovak** [comment]
i installed the file '.gitignore ' from new repository . There i chose the file with adding  .gitignore
